config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root to: 'restaurants#index'
  resources :restaurants, only: %i[index show new create ] do
    resources :reviews, only: %i[create]
  end

  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
    message: "%{value} is not a valid size" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: 'restaurant was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'review was successfully created'
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container mt-5">
    <h1 style= "padding-top = 50px;">Create a new restaurant</h1>
    <%= simple_form_for @restaurant do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
      <%= f.submit class: 'btn btn-outline-primary' %>
      <%= link_to "Back", restaurants_path, class: 'btn btn-outline-danger' %>
    <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <div class="container-fluid">
    <span class= "navbar-brand">Yelp MVP</span>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <span class="nav-item">
        <a> <%= link_to 'Create a restaurant', new_restaurant_path, class: "nav-link"%></a>
      </span>
    </div>
  </div>
</div>

<div class = 'container py-3'>
    <div class="cards">
      <% @restaurants.each do |resto|  %>
        <div class="card-category">
          <div class="card-body">
            <h5 class="card-title"><%= resto.name %></h5>
            <p class="card-text"><%= resto.address %></p>
            <p class="card-text"><%= resto.phone_number %></p>
            <p class="card-text"><%= resto.category %></p>
            <div class = "card-link">
              <%= link_to "see more", restaurant_path(resto), class: 'btn btn-outline-primary' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/restaurants/new.html.erb
 <div>
    <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class = 'container mt-5'>
  <div class = 'card'>
    <div class = 'card-body'>
      <p class='card-title'><strong><%= @restaurant.name %></strong></p>
      <p class='card-text'><%= @restaurant.address %></p>
      <p class='card-text'><%= @restaurant.phone_number %></p>
      <%= @restaurant.category %>
    </div>
    <div class = 'card-body'>
      <p><strong>Reviews</strong></p>
      <ul class='list-group'>
        <% @restaurant.reviews.each do |review| %>
          <li class='list-group-item'>
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <i class="fa-solid fa-star"></i>
                <% else %>
                  <i class="fa-regular fa-star"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </ul>
    </div>
    <div class = 'container'>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :rating, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to "Back", restaurants_path, class: 'btn btn-outline-danger' %>
      <% end %>
    </div>
  </div>
</div>